### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by mldemox** [minshu-kim/Recurrent-Elastic-Warp#6]
Traceback (most recent call last): File "eval_psnr.py", line 128, in <module> main(config, args) File "eval_psnr.py", line 113, in main eval(loader, H_model, model, args) File "eval_psnr.py", line 82, in eval flow = flow_hom + flows[-1]

**Comment by minshu-kim** [comment]
Can you share the full error log or screenshots?

**Comment by minshu-kim** [comment]
I will temporarily close this issue due to inactivity. Feel free to reopen if you don't resolve the problem.
